### PR TITLE
feat: examples added for distinctfield prop support

### PR DESCRIPTION
**Pull request by anik-ghosh-au7**
Examples added for distinctField & distinctFieldConfig props in ReactiveSearch vue components - which returns distinct results based on a specified field.

For further reference please look into this PR - https://github.com/appbaseio/reactivesearch/pull/1654

### CODE REVIEW

**Review by bietkul — CHANGES_REQUESTED** [review]
@anik-ghosh-au7 Why are you creating new components for each story? You can use the existing component and pass the `subProps` follow the existing examples.

**Comment by anik-ghosh-au7** [comment]
@bietkul I have made the changes

**Review by bietkul — CHANGES_REQUESTED** [review]
@anik-ghosh-au7 Use knobs for `distinctField` property so users can modify it.

**Comment by anik-ghosh-au7** [comment]
@bietkul I have updated the knobs for `distinctField` and `distinctFieldConfig` props in the examples - 

https://www.loom.com/share/0c83c688d7b4483281586f346d1c2b85

**Review by bietkul — APPROVED** [review]

**Pull request merged**
